# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFileButton.setGeometry(QtCore.QRect(30, 20, 140, 25))
        self.loadFileButton.setObjectName("loadFileButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 150, 17))
        self.label.setObjectName("label")
        self.inputSliceNum = QtWidgets.QLineEdit(self.centralwidget)
        self.inputSliceNum.setGeometry(QtCore.QRect(190, 70, 31, 21))
        self.inputSliceNum.setObjectName("inputSliceNum")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 70, 16, 17))
        self.label_2.setObjectName("label_2")
        self.totalSlice = QtWidgets.QLabel(self.centralwidget)
        self.totalSlice.setGeometry(QtCore.QRect(240, 70, 31, 17))
        self.totalSlice.setText("")
        self.totalSlice.setObjectName("totalSlice")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 120, 150, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 120, 150, 17))
        self.label_4.setObjectName("label_4")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(20, 150, 300, 300))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.segImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.segImageLabel.setGeometry(QtCore.QRect(470, 150, 300, 300))
        self.segImageLabel.setText("")
        self.segImageLabel.setObjectName("segImageLabel")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(350, 360, 89, 25))
        self.runButton.setObjectName("runButton")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(90, 460, 160, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.currentImg = QtWidgets.QLabel(self.centralwidget)
        self.currentImg.setGeometry(QtCore.QRect(140, 490, 16, 17))
        self.currentImg.setObjectName("currentImg")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 490, 16, 17))
        self.label_8.setObjectName("label_8")
        self.totalImg = QtWidgets.QLabel(self.centralwidget)
        self.totalImg.setGeometry(QtCore.QRect(180, 490, 21, 17))
        self.totalImg.setText("")
        self.totalImg.setObjectName("totalImg")
        self.filePathLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLabel.setGeometry(QtCore.QRect(200, 20, 460, 20))
        self.filePathLabel.setStyleSheet("background-color:\"transparent\"")
        self.filePathLabel.setFrame(False)
        self.filePathLabel.setReadOnly(True)
        self.filePathLabel.setObjectName("filePathLabel")
        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(350, 570, 89, 25))
        self.calculateButton.setObjectName("calculateButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 540, 120, 17))
        self.label_5.setObjectName("label_5")
        self.inputEDNum = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEDNum.setGeometry(QtCore.QRect(280, 540, 31, 21))
        self.inputEDNum.setObjectName("inputEDNum")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 600, 120, 17))
        self.label_6.setObjectName("label_6")
        self.inputESNum = QtWidgets.QLineEdit(self.centralwidget)
        self.inputESNum.setGeometry(QtCore.QRect(280, 600, 31, 21))
        self.inputESNum.setObjectName("inputESNum")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(480, 540, 81, 17))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 570, 81, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(480, 600, 131, 17))
        self.label_10.setObjectName("label_10")
        self.edVolume = QtWidgets.QLabel(self.centralwidget)
        self.edVolume.setGeometry(QtCore.QRect(630, 540, 67, 17))
        self.edVolume.setText("")
        self.edVolume.setObjectName("edVolume")
        self.esVolume = QtWidgets.QLabel(self.centralwidget)
        self.esVolume.setGeometry(QtCore.QRect(630, 570, 67, 17))
        self.esVolume.setText("")
        self.esVolume.setObjectName("esVolume")
        self.ejection_fraction = QtWidgets.QLabel(self.centralwidget)
        self.ejection_fraction.setGeometry(QtCore.QRect(630, 600, 67, 17))
        self.ejection_fraction.setText("")
        self.ejection_fraction.setObjectName("ejection_fraction")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(710, 540, 67, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(710, 570, 67, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(710, 600, 67, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(346, 170, 101, 16))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadFileButton.setText(_translate("MainWindow", "Load Nifti Image"))
        self.label.setText(_translate("MainWindow", "Current slice number :"))
        self.label_2.setText(_translate("MainWindow", "/"))
        self.label_3.setText(_translate("MainWindow", "Original Images"))
        self.label_4.setText(_translate("MainWindow", "Segmented Images"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.currentImg.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "/"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))
        self.label_5.setText(_translate("MainWindow", "ED Slice number :"))
        self.label_6.setText(_translate("MainWindow", "ES Slice number :"))
        self.label_7.setText(_translate("MainWindow", "ED Volume : "))
        self.label_9.setText(_translate("MainWindow", "ES Volume :"))
        self.label_10.setText(_translate("MainWindow", "Ejection Fraction : "))
        self.label_11.setText(_translate("MainWindow", "mm3"))
        self.label_12.setText(_translate("MainWindow", "mm3"))
        self.label_13.setText(_translate("MainWindow", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
